= Apache Camel Update Recipes

This project contains recipes to assist in the migration of Camel projects.

You can find the recipes in the src/main/resources/META-INF/rewrite directory.

The names of the recipes correspond to the Camel version they support, formatted as [major].[minor].yaml. To migrate from version X.Y to version A.B, apply all recipes with versions greater than X.Y and less than A.B.

For example, to migrate from version 3.8 to 4.4, you need to apply the recipes `*4.0.yaml*` and `*4.4.yaml*`.

== How to run from cmd

To apply recipes on a standalone Camel Project you can use maven plugin:

```

mvn -U org.openrewrite.maven:rewrite-maven-plugin:5.20.0:run \
-Drewrite.recipeArtifactCoordinates=org.apache.camel:camel-tooling-updates:4.7.0-SNAPSHOT \
-DactiveRecipes=org.apache.camel.updates.camel44.CamelQuarkusMigrationRecipe
-Drewrite.recipeFile=/org.apache.camel.updates/4.0.yaml
```


----------------- PR --------------------------------------------
This is a draft of simple migration module using Openrewrite recipes for Camel migration.
This version is a extraction of recipes from project https://github.com/quarkusio/quarkus-updates/ into a Camel repository.
Please look at the README.adoc to understand the module.

Here is a list with TODOs (the reason why this PR is a draft)
- This module should be standalone project.
It might be necessary to release new version of recipes and it wouldn't be possible if whole Camel has to be released as well.
- Better CLI for executing the migration would be nice. Look for example on quarkus https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0
It would be nice to use something like `camel update 4.4` (which in case of camel 3.x would trigger update to 4.0 and then to 4.4)