/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.asyncApi;

public class Aa20SecuritySchemaHttp extends Aa20AbstractSecuritySchema implements Aa20OrReferenceType<Aa20SecuritySchemaHttp> {

    private final String schema;
    private String bearerFormat;


    /**
     * @param schema The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
     */
    public Aa20SecuritySchemaHttp(String schema) {
        super(Type.http);
        this.schema = schema;
    }

    public String getSchema() {
        return schema;
    }

    public String getBearerFormat() {
        return bearerFormat;
    }

    /**
     * @param bearerFormat A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
     */
    public void setBearerFormat(String bearerFormat) {
        this.bearerFormat = bearerFormat;
    }
}
